### ISSUE TITLE
QA Testing: Emoji names are being truncated too soon in the picker

### ISSUE THREAD

**Issue by emilyacook** [mattermost/quality-assurance#10]
QA testing needed for issue https://github.com/mattermost/mattermost-server/issues/18430
# Issue Description
Daily

Repro: 
1. hover over a long emoji name in the picker

Observed: Custom Emoji button is causing the emoji name to truncate way earlier than it has to

 ![](image-2021-08-09-11-46-39-550.png|thumbnail) 

Expected: Allow the emoji text to run closer to the custom emoji button

----
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-37746

**Comment by alauregaillard** [comment]
Hi @emilyacook! Can I test it?

**Comment by lindy65** [comment]
Closing as the associated server issue has been closed.
