### ISSUE TITLE
QA Testing: Improve messaging in the add members to channel modal

### ISSUE THREAD

**Issue by emilyacook** [mattermost/quality-assurance#17]
QA testing needed for issue https://github.com/mattermost/mattermost-server/issues/17707
# Issue Description
From the channel menu, when you click "Add Members" there is a modal that states "Up to 20 can be added at a time". This message is confusing and only necessary if the user actually tries to add more than 20 people. To fix this:

1. Remove the text "You can add 20 more" from the modal

![](image-2021-04-30-13-57-07-407.png|width=200,height=183)

 
2. If the user adds 20 people to the input box, then show a message "Up to 20 can be added at a time" and do not allow them to type any more characters unless they remove a user from the input area 

![](image-20210601-155529.png|width=690,height=511)

Design link: [https://www.figma.com/file/U10zzjkOQd5bO2ekAnllpt/Add-Members-to-Channel?node-id=513%3A1](https://www.figma.com/file/U10zzjkOQd5bO2ekAnllpt/Add-Members-to-Channel?node-id=513%3A1|smart-link) 

User story: [https://community-daily.mattermost.com/core/pl/smbwy1w68jg6b8h17kjqyn6ojr](https://community-daily.mattermost.com/core/pl/smbwy1w68jg6b8h17kjqyn6ojr)

----
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-35366

**Comment by Enhmunh-E** [comment]
There is no design in that Figma link can you update it?
