### ISSUE TITLE
QA Testing: DND Expiry: Tomorrow is unclear as a menu option

### ISSUE THREAD

**Issue by emilyacook** [mattermost/quality-assurance#18]
QA testing needed for issue https://github.com/mattermost/mattermost-server/issues/17732
# Issue Description
There is a lack of clarity with the 'Tomorrow' option for the DND expiry/timer
Link to initial feedback: [https://community-daily.mattermost.com/core/pl/if5k57ozitfadxra5ieqigkn3w](https://community-daily.mattermost.com/core/pl/if5k57ozitfadxra5ieqigkn3w)

Tomorrow should display as 9:00 AM tomorrow. 

**Current Menu**

![](image-2021-05-19-16-04-37-917.png|width=200,height=183)

**Proposed solution:**

![](image-20210603-165122.png|width=58.333333333333336%)

**Google's example:**

![](image-2021-05-19-16-03-55-802.png|width=200,height=183)

{panel:bgColor=#eae6ff}
 **Design Notes**

  * Add an affordance that qualifies the ‘when’ the expiry will take place for the ‘Tomorrow’ event
  * We don’t need to include the affordance the times according in the same day
    * We have an additional ticket, already in-progress to surface the time set in the status menu under the DND option
{panel}

----
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-35885

**Comment by alauregaillard** [comment]
Hi @lindy65, you should closed that QA issue, the associated issue has been closed.
