### ISSUE TITLE
QA Testing: Update list of available timezones

### ISSUE THREAD

**Issue by emilyacook** [mattermost/quality-assurance#20]
QA testing needed for issue https://github.com/mattermost/mattermost-server/issues/16918
# Issue Description
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-32804)

Timezones must be enabled using the experimental config "ExperimentalTimezone"

______
 
This ticket is to update the current timezone selector UX in Account Settings > Display > Timezone

1. Update list of available timezones to this: https://github.com/dmfilipenko/timezones.json/blob/master/timezones.json

**Comment by alauregaillard** [comment]
Hi @lindy65, you should closed that QA issue, the associated issue has been closed.
