### ISSUE TITLE
QA Testing: Allow users to specify different desktop notification sounds per channel

### ISSUE THREAD

**Issue by emilyacook** [mattermost/quality-assurance#21]
QA testing needed for issue https://github.com/mattermost/mattermost-server/issues/16515
# Issue Description
When a user selects "Notification Preferences > Send Desktop Notifications", for a specific channel, we should add an option to this menu for "Notification Sound" 

**Mock-up:**

![image](https://user-images.githubusercontent.com/3277310/101539321-5b8ab400-396c-11eb-9c4b-aad4617965fc.png)

**Functionality:**

  * The channel notification preference should initially follow the global account setting notification preference
  * If user changes from the global defaults, a ‘reset to defaults’ button appears in the top right of the section. Clicking this will return the settings back to the global defaults
  * If the channel notification preference is changed here, it is then decoupled from the global setting.
  * If the user edits the channel preferences notification sound, it should no longer be linked to the notification sound selected in account settings.
  * If “For all activity” or “Only for mentions” is selected, a new section is added to the channel notifications settings to choose the notification sound.
  * If "Never" is selected, then hide the settings for "notification sound

**Note:** these settings already implemented at the Account Settings level (see Account Settings > Notifications > Desktop Notifications > Notification Sound, related ticket that was completed <MM-467>)), but this is introducing the same control at the channel level to specify specific sounds per channel. 

----
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-30432

**Comment by lindy65** [comment]
Hi @BabbarRaghav - so sorry, the associated server PR has been closed. I'll close this issue off for now until a new server issue is opened.

**Comment by BabbarRaghav** [comment]
No problem @lindy65
