### ISSUE TITLE
QA Testing: MM-36862: should remove user from participants

### ISSUE THREAD

**Issue by emilyacook** [mattermost/quality-assurance#22]
QA testing needed for issue https://github.com/mattermost/mattermost-server/pull/18451
# Issue Description
#### Summary

When deleting a reply in a thread we should also delete the participant
from the participants array. This should happen if they have no other
replies in that thread.

This commit fixes that.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-36862

#### Release Note

```release-note
NONE
```

**Comment by lindy65** [comment]
Thanks @alauregaillard - closing this issue as complete :)
