### ISSUE TITLE
QA Testing: MM-39106: Fix emoji size in post menu for one-click reactions

### ISSUE THREAD

**Issue by lindy65** [mattermost/quality-assurance#24]
QA testing needed for PR https://github.com/mattermost/mattermost-webapp/pull/9115
# Issue Description

#### Summary
Fix the size of the one-click reaction emojis.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-39106

#### Release Note

```release-note
NONE
```

**Comment by alauregaillard** [comment]
Hi! Can I be assigned please?
