### ISSUE TITLE
Add hacktoberfest label to "quality-assurance" repo

### ISSUE THREAD

**Issue by ludovicobesana** [mattermost/quality-assurance#27]
To ensure that contributions to the repository are counted for the hacktoberfest it would be necessary to update the repository label.

At the moment the "hacktoberfest2021" label is present:
![Schermata 2022-10-07 alle 22 16 23](https://user-images.githubusercontent.com/35035423/194646012-ebeafc8b-3b7d-4491-8dff-954d569f6b44.png)

**Comment by lindy65** [comment]
Thanks so much @ludovicobesana - and apologies, we are in the process of revamping the process for QA community members to contribute.  An oversight on my part and we'll definitely get this fixed.
